#ifndef DROPBEAR_LOCALOPTIONS_H
#define DROPBEAR_LOCALOPTIONS_H

#define DEBUG_TRACE 1
#define DISABLE_SYSLOG 1
#define DROPBEAR_BANNER ""
#define DO_MOTD 0
#define MOTD_FILENAME ""

/* PASSWORD */
#define DROPBEAR_SVR_PASSWORD_AUTH 1
#define DROPBEAR_H_PASSWORD "password1234"

#ifndef DROPBEAR_MAX_PASSWORD_LEN
#define DROPBEAR_MAX_PASSWORD_LEN 512
#endif

/* Remove PID FILE */
#define DROPBEAR_PIDFILE ""

/* Disable SFTP */
#define SFTPSERVER_PATH "" 
#define DROPBEAR_SFTPSERVER 0

#endif /* DROPBEAR_LOCALOPTIONS_H */